eureka:
  client:
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
server:
  port: ${PORT:8765}
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: shopping-user-api
        uri: lb://shopping-user-api
        predicates:
        - Path=/users/**, /address/**
      - id: shopping-product-api
        uri: lb://shopping-product-api
        predicates:
        - Path=/categories/**, /products/**, /sub_category/**
      - id: shopping-store-api
        uri: lb://shopping-store-api
        predicates:
        - Path=/orders/**
      - id: shopping-authentication-api
        uri: lb://shopping-authentication-api
        predicates:
        - Path=/auth/**
      - id: shopping-discounts-api
        uri: lb://shopping-discounts-api
        predicates:
        - Path=/coupons/**, /discounts/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

